"""New fields in user Model

Revision ID: 3208b9161434
Revises: db566f6eb981
Create Date: 2018-03-29 10:18:48.116213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3208b9161434'
down_revision = 'db566f6eb981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
